webdriver:
  browser: chrome
  headless: false

log_level: Logger::DEBUG

timeout:
  short: 8
  medium: 30
  long: 240

base_url:
  bampfa: https://bampfa-dev.cspace.berkeley.edu
  botgarden: https://botgarden-dev.cspace.berkeley.edu
  cinefiles: https://cinefiles-dev.cspace.berkeley.edu
  core: https://core.collectionspace.org
  pahma: https://pahma-dev.cspace.berkeley.edu
  ucjeps: https://ucjeps-dev.cspace.berkeley.edu/

credentials:
  core:
    admin_username: admin@core.collectionspace.org
    admin_password: Administrator
