webdriver:
  browser: chrome
  headless: false

log_level: Logger::DEBUG

timeout:
  short: 8
  medium: 30
  long: 240

deployment: core

bampfa:
  base_url: https://bampfa-dev.cspace.berkeley.edu
  admin:
    username: secret
    password: secret

botgarden:
  base_url: https://botgarden-dev.cspace.berkeley.edu
  admin:
    username: secret
    password: secret

cinefiles:
  base_url: https://cinefiles-dev.cspace.berkeley.edu
  admin:
    username: secret
    password: secret

core:
  base_url: https://core.collectionspace.org
  admin:
    username: secret
    password: secret

pahma:
  base_url: https://pahma-dev.cspace.berkeley.edu
  admin:
    username: secret
    password: secret

ucjeps:
  base_url: https://ucjeps-dev.cspace.berkeley.edu/
  admin:
    username: secret
    password: secret
