webdriver:
  browser: chrome
  headless: false

log_level: Logger::DEBUG

timeout:
  click: 1
  short: 8
  medium: 30
  long: 240

deployment: core

core:
  base_url: https://core.collectionspace.org
  admin:
    username: admin@core.collectionspace.org
    password: Administrator
